/**
 * GeographicDataProvider
 * Provides geographic entities that are natural features, oceans, seas, mountain ranges,
 * and global geographic landmarks that may not have standard Google Place records.
 */

export const NATURAL_GEOGRAPHIC_ENTITIES = [
  {
    id: 'geo-indian-ocean',
    name: 'Indian Ocean',
    formattedName: 'Indian Ocean (Global Oceanic Basin)',
    country: 'International Waters',
    region: 'Indo-Pacific',
    latitude: -10.0,
    longitude: 75.0,
    type: 'ocean',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'world',
    cameraDistance: 6.8,
    shortDescription: 'The third-largest ocean in the world, bounded by Asia to the north, Africa to the west, and Australia to the east.',
    tags: ['Ocean', 'Natural Feature', 'Marine Basin', 'Expedition'],
    isNaturalFeature: true,
  },
  {
    id: 'geo-pacific-ocean',
    name: 'Pacific Ocean',
    formattedName: 'Pacific Ocean (Largest Global Oceanic Basin)',
    country: 'International Waters',
    region: 'Circum-Pacific',
    latitude: 0.0,
    longitude: -160.0,
    type: 'ocean',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'world',
    cameraDistance: 7.2,
    shortDescription: 'The largest and deepest oceanic division on Earth, stretching from the Arctic in the north to the Southern Ocean.',
    tags: ['Ocean', 'Natural Feature', 'Marine Basin', 'Expedition'],
    isNaturalFeature: true,
  },
  {
    id: 'geo-atlantic-ocean',
    name: 'Atlantic Ocean',
    formattedName: 'Atlantic Ocean (Second-Largest Ocean)',
    country: 'International Waters',
    region: 'Transatlantic',
    latitude: 14.0,
    longitude: -38.0,
    type: 'ocean',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'world',
    cameraDistance: 7.0,
    shortDescription: 'The second-largest of the worlds oceans, separating the Americas from Europe and Africa.',
    tags: ['Ocean', 'Natural Feature', 'Marine Basin', 'Expedition'],
    isNaturalFeature: true,
  },
  {
    id: 'geo-arabian-sea',
    name: 'Arabian Sea',
    formattedName: 'Arabian Sea (Northern Indian Ocean)',
    country: 'International Waters',
    region: 'South Asia / Arabian Peninsula',
    latitude: 16.0,
    longitude: 65.0,
    type: 'sea',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'country',
    cameraDistance: 5.4,
    shortDescription: 'A region of the northern Indian Ocean bounded on the north by Pakistan and Iran, on the west by the Gulf of Aden and the Arabian Peninsula, and on the east by India.',
    tags: ['Sea', 'Natural Feature', 'Maritime Route', 'Coastal Waters'],
    isNaturalFeature: true,
  },
  {
    id: 'geo-bay-of-bengal',
    name: 'Bay of Bengal',
    formattedName: 'Bay of Bengal (Northeastern Indian Ocean)',
    country: 'International Waters',
    region: 'South / Southeast Asia',
    latitude: 15.0,
    longitude: 88.0,
    type: 'sea',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'country',
    cameraDistance: 5.4,
    shortDescription: 'The largest water region called a bay in the world, forming the northeastern part of the Indian Ocean.',
    tags: ['Sea', 'Bay', 'Natural Feature', 'Maritime Region'],
    isNaturalFeature: true,
  },
  {
    id: 'geo-mediterranean-sea',
    name: 'Mediterranean Sea',
    formattedName: 'Mediterranean Sea (Intercontinental Basin)',
    country: 'International Waters',
    region: 'Southern Europe / North Africa / Levant',
    latitude: 35.0,
    longitude: 18.0,
    type: 'sea',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'country',
    cameraDistance: 5.2,
    shortDescription: 'A sea connected to the Atlantic Ocean, surrounded by the Mediterranean Basin and almost completely enclosed by land.',
    tags: ['Sea', 'Natural Feature', 'Historic Basin', 'Coastal Waters'],
    isNaturalFeature: true,
  },
  {
    id: 'geo-himalayas',
    name: 'Himalayas',
    formattedName: 'Himalayas Mountain Range (Asia)',
    country: 'India / Nepal / Bhutan / China',
    region: 'Central & South Asia',
    latitude: 28.5,
    longitude: 84.0,
    type: 'mountain',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'country',
    cameraDistance: 4.8,
    shortDescription: 'The highest mountain range in the world, home to the worlds highest peaks including Mount Everest and K2.',
    tags: ['Mountain Range', 'Natural Feature', 'Alpine Trekking', 'High Altitude'],
    isNaturalFeature: true,
  },
  {
    id: 'geo-mount-everest',
    name: 'Mount Everest',
    formattedName: 'Mount Everest (Sagarmatha / Chomolungma)',
    country: 'Nepal / China',
    region: 'Mahalangur Himal, Himalayas',
    latitude: 27.9881,
    longitude: 86.9250,
    type: 'landmark',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'landmark',
    cameraDistance: 3.8,
    shortDescription: 'Earths highest mountain above sea level, located in the Mahalangur Himal sub-range of the Himalayas (8,848.86 m).',
    tags: ['Mountain Peak', 'World Wonder', 'Alpine Trekking', 'Extreme Altitude'],
    isNaturalFeature: true,
  },
  {
    id: 'geo-sahara-desert',
    name: 'Sahara Desert',
    formattedName: 'Sahara Desert (North Africa)',
    country: 'Algeria / Chad / Egypt / Libya / Mali / Mauritania / Morocco / Niger / Sudan / Tunisia',
    region: 'Northern Africa',
    latitude: 23.4,
    longitude: 12.6,
    type: 'desert',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'country',
    cameraDistance: 5.2,
    shortDescription: 'The largest hot desert in the world, covering an area of 9.2 million square kilometers across Northern Africa.',
    tags: ['Desert', 'Natural Feature', 'Dunes', 'Expedition'],
    isNaturalFeature: true,
  },
  {
    id: 'geo-amazon-rainforest',
    name: 'Amazon Rainforest',
    formattedName: 'Amazon Rainforest (Amazon Basin, South America)',
    country: 'Brazil / Peru / Colombia / Bolivia',
    region: 'South America',
    latitude: -3.4,
    longitude: -62.2,
    type: 'forest',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'country',
    cameraDistance: 5.0,
    shortDescription: 'The worlds largest tropical rainforest, famed for its extraordinary biodiversity and crisscrossed by thousands of rivers including the powerful Amazon River.',
    tags: ['Rainforest', 'Natural Feature', 'Ecosystem', 'Biodiversity'],
    isNaturalFeature: true,
  },
  {
    id: 'geo-eiffel-tower',
    name: 'Eiffel Tower',
    formattedName: 'Eiffel Tower, Champ de Mars, Paris, France',
    country: 'France',
    region: 'Île-de-France',
    latitude: 48.8584,
    longitude: 2.2945,
    type: 'landmark',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'landmark',
    cameraDistance: 3.85,
    shortDescription: 'A wrought-iron lattice tower on the Champ de Mars in Paris, named after engineer Gustave Eiffel.',
    tags: ['Landmark', 'Architecture', 'Iconic', 'Culture'],
  },
  {
    id: 'geo-taj-mahal',
    name: 'Taj Mahal',
    formattedName: 'Taj Mahal, Dharmapuri, Forest Colony, Agra, Uttar Pradesh, India',
    country: 'India',
    region: 'Uttar Pradesh',
    latitude: 27.1751,
    longitude: 78.0421,
    type: 'landmark',
    source: 'geographic_dataset',
    curated: false,
    zoomLevel: 'landmark',
    cameraDistance: 3.85,
    shortDescription: 'An ivory-white marble mausoleum on the south bank of the Yamuna river in Agra, commissioned by Mughal emperor Shah Jahan.',
    tags: ['UNESCO World Heritage', 'Landmark', 'Mughal Architecture', 'Seven Wonders'],
  },
];

export class GeographicDataProvider {
  static search(query) {
    if (!query) return [];
    const q = query.toLowerCase().trim();
    return NATURAL_GEOGRAPHIC_ENTITIES.filter((entity) => {
      return (
        entity.name.toLowerCase().includes(q) ||
        entity.formattedName.toLowerCase().includes(q) ||
        entity.region.toLowerCase().includes(q) ||
        entity.country.toLowerCase().includes(q) ||
        entity.tags.some((t) => t.toLowerCase().includes(q))
      );
    });
  }

  static getById(id) {
    return NATURAL_GEOGRAPHIC_ENTITIES.find((entity) => entity.id === id) || null;
  }
}
